import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const dmSans = DM_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that sets up global providers, styles, and metadata for the application.
 *
 * Wraps the application with font styling, Nuqs and tRPC providers, and includes a global toaster for notifications.
 *
 * @param children - The content to render within the application layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${dmSans.className} antialiased`}
        suppressHydrationWarning={true}
      >
        
        <NuqsAdapter>
        <TRPCReactProvider>

        {children}
        <Toaster/>

        </TRPCReactProvider>
        </NuqsAdapter>

      </body>
    </html>
  );
}
